### ISSUE TITLE
How to change the width of the login form

### ISSUE THREAD

**Issue by firestormdong** [vaadin/vaadin-login-flow#47]
My app has a long name, and I want to show it in one line, so need to change the login form wider.
![image](https://user-images.githubusercontent.com/20729067/52499031-56e9ee80-2b8f-11e9-89f8-ed555513407b.png)

Seems that this doesn't work:
loginOverlay.getElement().getStyle().set("width", "1000px");

**Comment by DiegoCardoso** [comment]
Hi @firestormdong,

Because of how `LoginOverlay` is implemented, which takes the full width and height available, you won't be able to change its width that way.

Rather, I would say that you could create a custom style module where you could define the desired width to the `[part="card"]` section, which is the container for the area you want to change.

In order to do that, you would:

- create a file `src/webapp/frontend/styles/custom-login-styles.html`
	```html
	<link rel="import" href="../bower_components/vaadin-login/theme/lumo/vaadin-login-overlay-styles.html">
	
	<dom-module id="custom-login-styles" theme-for="vaadin-login-overlay-wrapper">
	  <template>
	    <style>
	      [part="card"] {
	        width: 600px;
	      }
	
	      /* Small screen */
	      @media only screen
	      and (max-width: 500px) {
	        [part="card"] {
			  /* Adding back the width to 100% in small screens */
	          width: 100%;
	        }
	      }
	    </style>
	  </template>
	</dom-module>
	```
- and at the view you are defining your `LoginOverlay` instance, add
	```java
	@HtmlImport("frontend://styles/custom-login-styles.html")
	```

**Comment by firestormdong** [comment]
Hi @DiegoCardoso,

Thank you for the help, it works for me.

**Comment by DiegoCardoso** [comment]
Glad to help :-)
